## Introduction

In this lab we will implement a linear regression model with n variables (1 ==> n), we will use two libraries 
- numpy 
- matplotlib

we should have also some basics in linear algebra (the dot product, implementing vectors, matrix, ...)
let's get started !!

## The problem statement :

Imagine the data conteint 4 features (size, number of bedrooms, number of floors, the age of the house)

so with all fo this features w'll predicte the price of the house !!

| Size(m3) | Number of bedrooms | Number of floors | Age of the house | Price in 1000 MAD |
|-------------------------|--------------------|-----------------|------------------|---------------------|
| 2104                    | 5                  | 1               | 45               | 460                 |
| 1416                    | 3                  | 2               | 40               | 232                 |
| 852                     | 2                  | 1               | 35               | 178                  |


## Import the data :

In [94]:
import numpy as np
import matplotlib.pyplot as plt

In [95]:
X_train = np.array([[2104, 5, 1, 45],
           [1416, 3, 2, 40],
           [852, 2, 1, 35]])
Y_train = np.array([460, 232, 178])

In [96]:
# display the data :
print(X_train.shape)
print(f'the number of examples : {X_train.shape[0]}')
print(f'the number of features : {X_train.shape[1]}')
print(f'The type of X_train is {type(X_train)}')
print(f'The type of Y_train is {type(Y_train)}')
print(X_train)
print(Y_train)

(3, 4)
the number of examples : 3
the number of features : 4
The type of X_train is <class 'numpy.ndarray'>
The type of Y_train is <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


## The parameters :

### 1. the w parameter :

To define the size of w , we need to determine the number of features , for example if we have 5 features so we need (w1, w2. w3, w4, w5)

so m : the number of features in the problem statement w ==> (m, 1)


In [97]:
# define the m and n (the number of examples):
n = X_train.shape[0]
m = X_train.shape[1]

### 2. The b parameter :


the b is one value , (the one scalar)

In [98]:
#examples
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b_init = 785.1811367994083
print(f'W shape is {w_init.shape}\nand b shape is {type(b_init)}')

W shape is (4,)
and b shape is <class 'float'>


## Making a function that predict the price :

we have the linear function : f(X) = (W1 * X[0]    +    W2 * X[1]    + ... +    Wn * X[n - 1])    + b

OR   f(X) = W.X + b    Where w and b are verctors    and . is the dot product

### Implementation of the function :


In [99]:
def prediction_loop(X, W, b):
    '''
    X : the data 
    W : the first parameter of f 
    b : the second parameter of f
    return : the prediction 
    '''
    prediction = X.dot(W) + b
    return prediction[0]

In [100]:
# some examples
x = np.array([[2104, 5, 1, 45]])
print(x.shape)
print(prediction_loop(x, w_init, b_init))

(1, 4)
459.9999976194082


## calculate the cost function :


In [101]:
# cost function :
def cost_function(X, Y, W, b):
    '''
    X: the data without the target varaible
    Y: the target varaible
    W: the prameter (vector !)
    b: the second parameter 
    return: the cost !
    '''
    n = X.shape[0]
    m = X.shape[1]
    cost = 0
    for i in range(n):
        cost += ((X[i].dot(W) + b) - Y[i]) ** 2

    cost *= (1/(2*n))
    return cost

In [102]:
# some exmples
print(cost_function(X_train, Y_train, w_init,b_init))
print(prediction_loop(x, w_init, b_init))
print('-------------------------------------')
w = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b = 783
print(cost_function(X_train, Y_train, w, b))
print(prediction_loop(x, w, b))
print('-------------------------------------')
w1 = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
b1 = 789
print(cost_function(X_train, Y_train, w1, b1))
print(prediction_loop(x, w1, b1))


1.5578904330213735e-12
459.9999976194082
-------------------------------------
2.3786825199276525
457.81886081999994
-------------------------------------
7.291851679927477
463.81886081999994


## Gradient descente multi variable (compute the partial derivate)

the algorithm is also the same thing compared with one variable , w'll add the partial derivates of f  

we will start with calculating the partail derivates:

In [103]:
def compute_gradient(X, Y, W, b):
    '''
    X : the data without target variable
    Y : the data related to the target varaible
    W : the first vector parameter
    b : the second parameter 
    return :
           a list that conteint the partial DR
    '''
    n = X.shape[0]
    m = X.shape[1]
    dj_w = np.zeros((m,))
    dj_b = 0

    for i in range(n):
        for j in range(m):
            dj_w[j] += (1/ n) * (((X[i].dot(W) + b) - Y[i]) * X[i][j])
        dj_b += (1/n) * ((X[i].dot(W) + b) - Y[i])

    return dj_w, dj_b
        

## Gradient descente :


we will now implement the algo of bach gradient descente(par lot)

In [104]:
import copy
import math

In [105]:
def gradient_descent(X, Y, w_in, b_in, alpha, num_iter, compute_gradient, cost_function):
    '''
    X: the data without target varaible
    Y: the data related to the target varaible
    w_in : the first parameter initialisation
    b_in : the seconde parameter initialisation
    alpha : the rate learning 
    num_iter : the number of itertions in the algo
    compute_gradient : the function that calculate the partial derivations
    const_function : the function that calculate the cost of each parameters
    return :
            the best parameters that optimazing the cost function (the same thing of one variable !!)
    '''
    n = X.shape[0]
    m = X.shape[1]
    j_histo = []
    w = copy.deepcopy(w_in)
    b = b_in

    for i in range(num_iter):
        dj_w, dj_b = compute_gradient(X, Y, w, b)

        w = w - alpha * (dj_w)
        b = b - alpha * (dj_b)

        j_histo.append(cost_function(X, Y, w, b))


        if i % (math.ceil(num_iter / 10)) == 0 :
            print(f"Iteration {i:4d}: Cost {j_histo[-1]:8.2f} ")

    return w, b, j_histo

In [106]:
# some examlpes :
w_in = np.zeros_like(w_init)
b_in = 0
iteration = 1000
alpha = 5.0e-7
w_f, b_f, j_final = gradient_descent(X_train, Y_train, w_in, b_in, alpha, iteration, compute_gradient, cost_function)
print(f"b,w found by gradient descent: {b_f:0.2f},{w_f} ")

Iteration    0: Cost  2529.46 
Iteration  100: Cost   695.99 
Iteration  200: Cost   694.92 
Iteration  300: Cost   693.86 
Iteration  400: Cost   692.81 
Iteration  500: Cost   691.77 
Iteration  600: Cost   690.73 
Iteration  700: Cost   689.71 
Iteration  800: Cost   688.70 
Iteration  900: Cost   687.69 
b,w found by gradient descent: -0.00,[ 0.20396569  0.00374919 -0.0112487  -0.0658614 ] 


In [107]:
# doing some prediction
x = np.array([[2104, 5, 1, 45]])
print('predict value : ', prediction_loop(x, w_f, b_f), 'target varaible :', Y_train[0])
print('-------------------------------------')
x1 = np.array([[1416, 3, 2, 40]])
print('predict value : ', prediction_loop(x1, w_f, b_f), 'target varaible :', Y_train[1])
print('-------------------------------------')
x2 = np.array([[852, 2, 1, 35]])
print('predict value : ', prediction_loop(x2, w_f, b_f), 'target varaible :', Y_train[2])
print('-------------------------------------')


predict value :  426.18530497189204 target varaible : 460
-------------------------------------
predict value :  286.1674720078562 target varaible : 232
-------------------------------------
predict value :  171.46763087132317 target varaible : 178
-------------------------------------


## Building the model regression 

In [124]:
class LinearRegression:

    def __init__(self, learning_rate=0.01, iteration=1000):
        self.learning_rate = learning_rate
        self.iteration = iteration
        self.omega = None
        self.cost_histor = []


    def iniatlise_parameter(self, n):
        self.omega = np.zeros(n)
        self.bais = 0


    def cost_function(self, X, Y):
        '''
        X: the data without the target varaible
        Y: the target varaible
        return: the cost !
        '''
        n = X.shape[0]
        m = X.shape[1]
        cost = 0
        for i in range(n):
            cost += ((X[i].dot(self.omega) + self.bais) - Y[i]) ** 2
    
        cost *= (1/(2*n))
        return cost


    def compute_gradient(self, X, Y):
        '''
        X : the data without target variable
        Y : the data related to the target varaible
        return :
               a list that conteint the partial DR
        '''
        n = X.shape[0]
        m = X.shape[1]
        dj_w = np.zeros(m)
        dj_b = 0
    
        for i in range(n):
            for j in range(m):
                dj_w[j] += (1/ n) * (((X[i].dot(self.omega) + self.bais) - Y[i]) * X[i][j])
            dj_b += (1/n) * ((X[i].dot(self.omega) + self.bais) - Y[i])
    
        return dj_w, dj_b


    def gradient_descent(self, X, Y):
        '''
        X: the data without target varaible
        Y: the data related to the target varaible
        return :
                nothing (some changes)
        '''
        n = X.shape[0]
        m = X.shape[1]
        for i in range(self.iteration):
            dj_w, dj_b = self.compute_gradient(X, Y)
    
            self.omega = self.omega - self.learning_rate * (dj_w)
            self.bais = self.bais - self.learning_rate * (dj_b)
    
            self.cost_histor.append(self.cost_function(X, Y))
    
    
            #if i % (math.ceil(self.iteration / 10)) == 0 :
                #print(f"Iteration {i:4d}: Cost {self.cost_histor} ")


    def fit(self, X, Y):
        '''
        X: the data without target varaible
        Y: the data related to the target varaible
        return :
                nothing (just fiting the model)
        '''

        # initialize the parameters
        self.iniatlise_parameter(X.shape[1])

        #run the gradient descent
        self.gradient_descent(X, Y)


    def predict(self, X):
        '''
        X :  the data
        return : the prediction
        '''
        return X.dot(self.omega) + self.bais


    def MSE(self, y_true, y_predict):
        '''
        y_true : the values in target variable
        y_predict : the values in the prediction
        '''

        return np.mean((y_true - y_predict) ** 2)


    def R2_score(self, y_true, y_predict):
        '''
        y_true : the values in target variable
        y_predict : the values in the prediction
        '''
        mean_y_true = np.mean(y_true)
        ss_tot = np.sum((y_true - mean_y_true) ** 2)
        ss_res = np.sum((y_true - y_predict) ** 2)

        return (1 - (ss_res / ss_tot))
                

### Examples : 

In [122]:
print(X_train[0][0])

2104


In [125]:
# create the class
model = LinearRegression(5.0e-7, 1000)

# fiting the model
model.fit(X_train, Y_train)

# make prediction 
predictions = model.predict(X_train)

## Check predictions
print("Predictions:", predictions)

## Evaluate the model
MSE = model.MSE(Y_train, predictions)
R2 = model.R2_score(Y_train, predictions)

print("MSE:", MSE)
print("R² Score:", R2)

Predictions: [426.18530497 286.16747201 171.46763087]
MSE: 1373.406823333041
R² Score: 0.908047213220873


## Upgrading 

.......................