# **Decison TREE** :

### 1. Importing the libiraries :

In [1]:
import numpy as np
import matplotlib.pyplot as plt


### 2. The problem :

Suppose you're starting a business that grows and sells wild mushrooms.

- Since not all mushrooms are safe to eat, you'd like to figure out if a mushroom is edible or poisonous based on its physical features.
- You already have some data that can help with this.

**Can you use this data to find out which mushrooms are safe to sell?**

### 3. The data set :

we have 10 training examples of mushrooms , so each training example we have 3 features :
- **cap color** : this is the color of mushrooms (brown or red)
- **stalk shape** : the shape of the legd (/\ or \/)
- **Solitary** : is individual mushrooms or not (yes or no)
- **Edible** : the target variable 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/y47h6FP/Capture-d-cran-2024-10-13-135850.png" alt="Capture-d-cran-2024-10-13-135850" border="0"></a>

### 4. One-hot encoding :

one-hot encoding is a commonly used method to transform categorical variables into numerical variables. In this type of encoding, each unique category of a variable is converted into a new binary column, where a 1 indicates the presence of that category, and a 0 its absence.

Here's how you can use Pandas' pd.get_dummies method to perform one-hot encoding on a DataFrame(we will not use it)==>

because we have a small data set so we will encode it manually

X_train contains three features for each example:
- Brown color (A value of 1 indicates a "Brown" cap color and 0 indicates a "Red" cap color).
- Tapered shape (A value of 1 indicates a "Tapered stem shape" and 0 indicates a "Broad stem shape").
- Solitary (A value of 1 indicates "Yes" and 0 indicates "No").


y_train represents whether the mushroom is edible:
- y = 1 indicates edible.
- y = 0 indicates poisonous.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/DgVCHmQ/aa.png" alt="aa" border="0"></a>

In [3]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [4]:
print("First the 5 first elements of X_train:\n", X_train[:5])
print("Type of X_train:",type(X_train))
print("First the 5 first elements of y_train:", y_train[:5])
print("Type of y_train:",type(y_train))

First the 5 first elements of X_train:
 [[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]]
Type of X_train: <class 'numpy.ndarray'>
First the 5 first elements of y_train: [1 1 0 0 1]
Type of y_train: <class 'numpy.ndarray'>


In [5]:
#verify the shapes od the data set :
print ('The shape of X_train is:', X_train.shape)
print ('The shape of y_train is: ', y_train.shape)
print ('Number of training examples (m):', len(X_train))

The shape of X_train is: (10, 3)
The shape of y_train is:  (10,)
Number of training examples (m): 10


### 5.decision tree Algorithm :

In this lab, you will build a decision tree based on the provided dataset.
Remember that the steps to build a decision tree are as follows:

- 1.Start with all the examples at the root node.
- 2.Calculate the information gain for each possible split based on all the features, and choose the one that offers the highest information gain.
- 3.Split the dataset based on the selected feature and create the left and right branches of the tree.
- 4.Repeat the splitting process until the stopping criteria are met.


In this lab, you will implement the following functions, which will allow you to split a node into left and right branches using the feature with the highest information gain:

- Calculate entropy at a node.
- Split the dataset at a node into left and right branches based on a given feature.
- Calculate the information gain of a split based on a given feature.
- Choose the feature that maximizes information gain


Then, you will use the helper functions you've implemented to build a decision tree by repeating the splitting process until the stopping criteria are met. For this lab, the chosen stopping criterion is to set a maximum depth of 2.

#### **a. calculate the entropy :**

In [64]:
def compute_entropy(y):
    '''
    y : the data set contient the features
    Return : the entropy
    '''
    if len(y) == 0:
        return 0
    else :
        p1 = len([y[i] for i in range(len(y)) if y[i] == 1]) / len(y)
        if p1 == 0 or p1 == 1:
            return 0
        else:
            entropy = -p1 * np.log2(p1) - (1 - p1) * np.log2(1 - p1)
            return entropy

In [65]:
# the entropy for this example is 1
print("Entropy at root node: ", compute_entropy(y_train))

Entropy at root node:  1.0


#### **b. spliting the data set at the left and right brsnches** :

Next, you will write a helper function called split_dataset that takes the data at a node and a feature to split on, then divides it into left and right branches. Later in this lab, you will implement code to calculate the quality of the split.

The function takes as input the training data, a list of the indices of the data points at the node, and the feature on which you want to split.
It divides the data and returns the subset of indices in the left and right branches.
For example, suppose we start at the root node (so node_indices = [0,1,2,3,4,5,6,7,8,9]), and we choose to split based on feature 0, which is cap color (brown or not). The output of the function would then be left_indices = [0,1,2,3,4,7,9] (data points with brown caps) and right_indices = [5,6,8] (data points without brown caps).

In [66]:
def split_dataset(X, indices, I):
    '''
    X : the train data set
    indices : the indices of trainig examples
    I : the indice of the feature at the node 
    Return : the left indices and the right indices after spliting 
    '''
    w_right = []
    w_left = []
    for i in indices:
        if X[i][I] == 1:
            w_left.append(i)
        else:
            w_right.append(i)


    return w_left, w_right

In [67]:
# Case 1
root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# Feel free to play around with these variables
# The dataset only has three features, so this value can be 0 (Brown Cap),1 (Tapering Stalk Shape) or 2 (Solitary)
feature = 0
left_indices, right_indices = split_dataset(X_train, root_indices, feature)
print("CASE 1:")
print("Left indices: ", left_indices)
print("Right indices: ", right_indices)
# Case 2
root_indices_subset = [0, 2, 4, 6, 8]
left_indices, right_indices = split_dataset(X_train, root_indices_subset,feature)
print("CASE 2:")
print("Left indices: ", left_indices)
print("Right indices: ", right_indices)

CASE 1:
Left indices:  [0, 1, 2, 3, 4, 7, 9]
Right indices:  [5, 6, 8]
CASE 2:
Left indices:  [0, 2, 4]
Right indices:  [6, 8]


#### **c.Calculating Information Gain**

Next, you will write a function called `information_gain` that takes as input the training data, the indices at a node, and a feature to split on, then returns the information gain from the split.
##
## Information Gain Formula

**Information Gain** = H(p<sub>node</sub>) - (w<sub>left</sub> × H(p<sub>left</sub>) + w<sub>right</sub> × H(p<sub>right</sub>##))

## Explanation:

- **H(p<sub>node</sub>)** is the entropy at the node.
- **H(p<sub>left</sub>)** and **H(p<sub>right</sub>)** are the entropies of the left and right branches resulting from the split.
- **w<sub>left</sub>** and **w<sub>right</sub>** are the proportions of examples in the left and right branches, respectively.

**Note:** You can use the `compute_entropy()` function you implemented earlier to calculate the entropy.


In [68]:
def compute_information_gain(X, y, node_indices, feature):
    '''
    X : the train data set 
    y : the target variable
    node_indices : the indices of the train set
    feature : the feature that we will split the data set
    Return : the infromation gain the cost
    '''
    Hp1_node = compute_entropy(y)
    w_l, w_r = split_dataset(X, node_indices, feature)
    y_l = [y[i] for i in w_l]
    y_r = [y[i] for i in w_r]
    Hp_left = compute_entropy(y_l)
    Hp_right = compute_entropy(y_r)
    w_left = len(w_l) / (len(w_l) + len(w_r))
    w_right = len(w_r) / (len(w_l) + len(w_r))
    gain = Hp1_node - (w_left * Hp_left + w_right * Hp_right)
    return gain

In [69]:
info_gain0 = compute_information_gain(X_train, y_train, root_indices, feature=0)
print("Information Gain from splitting the root on brown cap: ", info_gain0)
info_gain1 = compute_information_gain(X_train, y_train, root_indices, feature=1)
print("Information Gain from splitting the root on tapering stalk shape: ", info_gain1)
info_gain2 = compute_information_gain(X_train, y_train, root_indices, feature=2)
print("Information Gain from splitting the root on solitary: ", info_gain2)

Information Gain from splitting the root on brown cap:  0.034851554559677034
Information Gain from splitting the root on tapering stalk shape:  0.12451124978365313
Information Gain from splitting the root on solitary:  0.2780719051126377


#### d.Finding the Best Split :

Now, let's write a function to obtain the best feature to split on by calculating the information gain for each feature, as we did earlier, and returning the feature that provides the maximum information gain.

The function is called `get_best_split()`.


In [70]:
def get_best_split(X, y, node_indices):
    '''
    X : the train set
    y : this is the target varaible
    node_indices : the indices of the data set 
    Return : best feature (the indice of the feature)
    '''
    features_number = len(X[0])
    list_grain = {}
    for i in range(features_number):
        gain = compute_information_gain(X, y, node_indices, i)
        list_grain[i] = gain
    liste = list(list_grain.values())
    maxi = max(liste)
    f = -1
    for j in list_grain.keys():
        if list_grain[j] == maxi:
            f = j
            break

    return f
    

In [71]:
best_feature = get_best_split(X_train, y_train, root_indices)
print("Best feature to split on: %d" % best_feature)

Best feature to split on: 2


### 6. Implementing the decision tree algo : 

In [72]:
def build_tree_recursive(X, y, node_indices, branche_name, max_depth, current_depth):
    '''
    X : the data set (train set)
    y : the target variable
    branche_name : the branche name of the tree ['Root', 'Left', 'Right']
    max_depth : the maximum of the tree
    current_depth : the current  level 
    Return : the decision tree 
    '''
    if current_depth == max_depth :
        formatting = " " * current_depth + "-" * current_depth
        print(formatting, "%s leaf node with indices" % branche_name, node_indices)
        return
    best_feature = get_best_split(X, y, node_indices)
    formatting = "-" * current_depth
    print("%s Depth %d, %s: Split on feature: %d" % (formatting, current_depth, branche_name, best_feature))
    left_indices, right_indices = split_dataset(X, node_indices, best_feature)

    build_tree_recursive(X=X, y=y, node_indices=left_indices, branche_name='Left', max_depth=max_depth, current_depth=(current_depth + 1))
    build_tree_recursive(X=X, y=y, node_indices=right_indices, branche_name='Right', max_depth=max_depth, current_depth=current_depth + 1)

In [78]:
build_tree_recursive(X_train, y_train, root_indices, "Root", max_depth=2, current_depth=0)

 Depth 0, Root: Split on feature: 2
- Depth 1, Left: Split on feature: 0
  -- Left leaf node with indices [0, 1, 4, 7]
  -- Right leaf node with indices [5]
- Depth 1, Right: Split on feature: 1
  -- Left leaf node with indices [8]
  -- Right leaf node with indices [2, 3, 6, 9]


this is the implimentation of how the decision trees works 

**in the next nchaalah we will create a class named DecisionTree that contient all function (predict , fit , score ...)**